if(CMAKE_SYSTEM_NAME STREQUAL "Android")
    message(STATUS "Building for Android")
elseif(CMAKE_SYSTEM_NAME STREQUAL "Windows")
    message(STATUS "Building for Windows")
elseif(CMAKE_SYSTEM_NAME STREQUAL "Linux")
    message(STATUS "Building for Linux")
else()
    message(WARNING "Unknown system: ${CMAKE_SYSTEM_NAME}")
endif()

if (MSVC)  # Visual Studio
    message(STATUS "==Configuring for Visual Studio==")
    add_definitions(-DNOMINMAX)

    if ("${CMAKE_GENERATOR}" MATCHES "(Win64|IA64)")
        set(TARGET_ARCH "x64")
    elseif ("${CMAKE_GENERATOR_PLATFORM}" MATCHES "ARM64")
        set(TARGET_ARCH "ARM64")
    elseif ("${CMAKE_GENERATOR}" MATCHES "ARM")
        set(TARGET_ARCH "ARM")
    elseif ("${CMAKE_SIZEOF_VOID_P}" STREQUAL "8")
        set(TARGET_ARCH "x64")
    else ()
        set(TARGET_ARCH x86)
    endif ()
elseif(CMAKE_SYSTEM_NAME STREQUAL "Linux")
    message(STATUS "==Configuring for Linux==")
    add_link_options(-Wl,--disable-new-dtags)
else ()  # Android Studio
    message(STATUS "Configuring for Android Studio")
    set(CMAKE_CXX_FLAGS_DEBUG "$ENV{CXXFLAGS} -O0 -Wall -g -ggdb")
    set(CMAKE_CXX_FLAGS_RELEASE "$ENV{CXXFLAGS} -O3")
    set(CMAKE_EXE_LINKER_FLAGS_DEBUG "${CMAKE_EXE_LINKER_FLAGS_DEBUG} -s")
    set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -Wl,-rpath=./")

    set(TARGET_ARCH ${ANDROID_ABI})
endif ()

message(STATUS "TARGET_ARCH: ${TARGET_ARCH}")